## broadcasting

In [1]:
import numpy as np
a = np.array([0,1,2])
m = np.ones((3,3))
print(m)
print(m+a)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[1. 2. 3.]
 [1. 2. 3.]
 [1. 2. 3.]]


In [2]:
a = np.arange(3)
b = np.arange(3)[:, np.newaxis]
print(a)
print(b)

[0 1 2]
[[0]
 [1]
 [2]]


In [3]:
a+b  #broadcasting

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])