## numpy array : universay functions - ufunc

In [6]:
## to speed up, the main point is vectorizing
import numpy as np
np.random.seed(0)

def compute_reciprocals(values):
    output = np.empty(len(values))
    for i in range(len(values)):
        output[i] = 1.0/values[i]
    return output

In [7]:
values = np.random.randint(1,10, size = 5)
compute_reciprocals(values)

array([0.16666667, 1.        , 0.25      , 0.25      , 0.125     ])

In [8]:
big_array = np.random.randint(1, 100, size = 1000000)
%timeit compute_reciprocals(big_array)

1.44 s ± 19 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [11]:
print(compute_reciprocals(values))
print(1.0/values)

[0.16666667 1.         0.25       0.25       0.125     ]
[0.16666667 1.         0.25       0.25       0.125     ]


In [12]:
%timeit (1.0/big_array)

2.57 ms ± 12.1 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [13]:
np.arange(5) / np.arange(1,6)

array([0.        , 0.5       , 0.66666667, 0.75      , 0.8       ])

In [17]:
np.arange(9).reshape((3,3))

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [19]:
##ufuncs
x = np.arange(4)
print(x)
print(x+5)
print(x-5)
print(x*2)
print(x/2)
print(x//2)
print(-x)
print(x**2)
print(x%2)

[0 1 2 3]
[5 6 7 8]
[-5 -4 -3 -2]
[0 2 4 6]
[0.  0.5 1.  1.5]
[0 0 1 1]
[ 0 -1 -2 -3]
[0 1 4 9]
[0 1 0 1]


In [20]:
-(0.5*x +1) **2

array([-1.  , -2.25, -4.  , -6.25])

In [25]:
##np.add
##np.subtract
##np.negative
##np.multiply
##np.divide
##np.floor_divide
##np.power
##np.mod
print(x)
print(np.add(x,2))
print(np.subtract(x,5))
print(np.negative(x))
print(np.multiply(x,3))
print(np.divide(x,2))
print(np.floor_divide(x,3))
print(np.power(x,5))
print(np.mod(x,2))

[0 1 2 3]
[2 3 4 5]
[-5 -4 -3 -2]
[ 0 -1 -2 -3]
[0 3 6 9]
[0.  0.5 1.  1.5]
[0 0 0 1]
[  0   1  32 243]
[0 1 0 1]


In [34]:
##np.absolute()
##np.linspace()
##np.exp()
##np.exp2
##np.power()
##np.sin()
##np.cos()
##np.tan()

x = np.array([-2, -1, 0, 1,2])
print(abs(x))
print(np.absolute(x))
print(np.abs(x))
print(np.abs([3-4j, 4-3j, 2+0j]))

theta = np.linspace(0,np.pi,3)
print(theta)
print(np.sin(theta))
print(np.cos(theta))
print(np.tan(theta))

print(np.exp(x))  #e^x
print(np.exp2(x)) #2^x
print(np.power(3,np.abs(x))) #3^x

[2 1 0 1 2]
[2 1 0 1 2]
[2 1 0 1 2]
[5. 5. 2.]
[0.         1.57079633 3.14159265]
[0.0000000e+00 1.0000000e+00 1.2246468e-16]
[ 1.000000e+00  6.123234e-17 -1.000000e+00]
[ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]
[0.13533528 0.36787944 1.         2.71828183 7.3890561 ]
[0.25 0.5  1.   2.   4.  ]
[9 3 1 3 9]


In [30]:
##np.arcsin()
##np.arccos()
##np.arctan()

x = [-1, 0, 1]
print(x)
print(np.arcsin(x))
print(np.arccos(x))
print(np.arctan(x))

[-1, 0, 1]
[-1.57079633  0.          1.57079633]
[3.14159265 1.57079633 0.        ]
[-0.78539816  0.          0.78539816]


In [37]:
##np.log()  ln(x)
##np.log2()  log2()
##np.log10()  log10()
##np.expm1()  exp() -1
##np.log1p()  log(1+ )

x = np.arange(1,5)
print(x)
print(np.log(x))
print(np.log2(x))
print(np.log10(x))
print(np.expm1(x))
print(np.log1p(x))

[1 2 3 4]
[0.         0.69314718 1.09861229 1.38629436]
[0.        1.        1.5849625 2.       ]
[0.         0.30103    0.47712125 0.60205999]
[ 1.71828183  6.3890561  19.08553692 53.59815003]
[0.69314718 1.09861229 1.38629436 1.60943791]


In [39]:
## specail ufunc

from scipy import special

x = [1 ,5, 10]
print(special.gamma(x))
print(special.gammaln(x))
print(special.beta(x,2))


[1.0000e+00 2.4000e+01 3.6288e+05]
[ 0.          3.17805383 12.80182748]
[0.5        0.03333333 0.00909091]


In [40]:
x = np.array([0, 0.3, 0.7, 1.0])
print(special.erf(x))
print(special.erfc(x))
print(special.erfinv(x))

[0.         0.32862676 0.67780119 0.84270079]
[1.         0.67137324 0.32219881 0.15729921]
[0.         0.27246271 0.73286908        inf]
