In [1]:
import numpy as np

##np.<tab>
##np?

In [3]:
np?

Type:        module
String form: <module 'numpy' from '/home/alex/.local/lib/python3.6/site-packages/numpy/__init__.py'>
File:        ~/.local/lib/python3.6/site-packages/numpy/__init__.py
Docstring:  
NumPy
=====

Provides
  1. An array object of arbitrary homogeneous items
  2. Fast mathematical operations over arrays
  3. Linear Algebra, Fourier Transforms, Random Number Generation

How to use the documentation
----------------------------
Documentation is available in two forms: docstrings provided
with the code, and a loose standing reference guide, available from
`the NumPy homepage <https://www.scipy.org>`_.

We recommend exploring the docstrings using
`IPython <https://ipython.org>`_, an advanced Python shell with
TAB-completion and introspection capabilities.  See below for further
instructions.

The docstring examples assume that `numpy` has been imported as `np`::

  >>> import numpy as np

Code snippets are indicated by three greater-than signs::

  >>> x = 42
  >>> x = x +

##np.array() - all elements must be same type
##dtype option to set data type

In [5]:
temp = np.array([1,2,3,4], dtype='float32')

In [6]:
type(temp[0])

numpy.float32

In [7]:
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [8]:
np.ones((3,5), dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [10]:
np.full((3,5), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [11]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [12]:
np.linspace(0,1,5) # 5 elements between 0 and 1

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [14]:
np.random.random((3,3))

array([[0.06888508, 0.02786184, 0.26119338],
       [0.26009612, 0.22350775, 0.66168897],
       [0.82793878, 0.12917182, 0.68178125]])

In [16]:
np.random.normal(0,1,(3,3)) # mean =  1, standard deviation = 1, random number

array([[-0.12336235,  0.1160541 , -1.17261912],
       [ 0.7337218 , -0.05360378, -0.56449651],
       [ 1.00068628,  1.5656137 ,  1.55359601]])

In [17]:
np.random.randint(0,10, (3,3)) # random int between 0 and 10

array([[4, 1, 7],
       [2, 6, 0],
       [2, 6, 1]])

In [18]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [19]:
np.empty(3)

array([1., 1., 1.])

In [20]:
np.empty((3,3))

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])


## NumPy data type
##bool
##int_ = long type in C
##intc = int type in c
##intp = ssize_t in C, using for indexing
##int8 = 1 byte
##int16 = 2 byte
##int32 = 4 byte
##int64 = 8 byte
##uint8 = unsigned 1 byte
##uint16 = unsigned 2 byte
##uint32 = unsigned 4 byte
##uint64 = unsigned 8 byte
##float_ = float 64
##float16 = half precision floating point
##float32 = single precision floating point
##float64 = double precision floating point
##conplex_ = complex128
##complex64 = ?
##complex128 = ?