In [1]:
import numpy as np

##np.<tab>
##np?

In [3]:
np?

Type:        module
String form: <module 'numpy' from '/home/alex/.local/lib/python3.6/site-packages/numpy/__init__.py'>
File:        ~/.local/lib/python3.6/site-packages/numpy/__init__.py
Docstring:  
NumPy
=====

Provides
  1. An array object of arbitrary homogeneous items
  2. Fast mathematical operations over arrays
  3. Linear Algebra, Fourier Transforms, Random Number Generation

How to use the documentation
----------------------------
Documentation is available in two forms: docstrings provided
with the code, and a loose standing reference guide, available from
`the NumPy homepage <https://www.scipy.org>`_.

We recommend exploring the docstrings using
`IPython <https://ipython.org>`_, an advanced Python shell with
TAB-completion and introspection capabilities.  See below for further
instructions.

The docstring examples assume that `numpy` has been imported as `np`::

  >>> import numpy as np

Code snippets are indicated by three greater-than signs::

  >>> x = 42
  >>> x = x +

##np.array() - all elements must be same type
##dtype option to set data type

In [5]:
temp = np.array([1,2,3,4], dtype='float32')

In [6]:
type(temp[0])

numpy.float32

In [7]:
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [8]:
np.ones((3,5), dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [10]:
np.full((3,5), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [11]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [12]:
np.linspace(0,1,5) # 5 elements between 0 and 1

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [14]:
np.random.random((3,3))

array([[0.06888508, 0.02786184, 0.26119338],
       [0.26009612, 0.22350775, 0.66168897],
       [0.82793878, 0.12917182, 0.68178125]])

In [16]:
np.random.normal(0,1,(3,3)) # mean =  1, standard deviation = 1, random number

array([[-0.12336235,  0.1160541 , -1.17261912],
       [ 0.7337218 , -0.05360378, -0.56449651],
       [ 1.00068628,  1.5656137 ,  1.55359601]])

In [17]:
np.random.randint(0,10, (3,3)) # random int between 0 and 10

array([[4, 1, 7],
       [2, 6, 0],
       [2, 6, 1]])

In [18]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [19]:
np.empty(3)

array([1., 1., 1.])

In [20]:
np.empty((3,3))

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])


## NumPy data type
##bool
##int_ = long type in C
##intc = int type in c
##intp = ssize_t in C, using for indexing
##int8 = 1 byte
##int16 = 2 byte
##int32 = 4 byte
##int64 = 8 byte
##uint8 = unsigned 1 byte
##uint16 = unsigned 2 byte
##uint32 = unsigned 4 byte
##uint64 = unsigned 8 byte
##float_ = float 64
##float16 = half precision floating point
##float32 = single precision floating point
##float64 = double precision floating point
##conplex_ = complex128
##complex64 = ?
##complex128 = ?

In [23]:
import numpy as np
np.random.seed(0)  # same seed same random system

x1 = np.random.randint(10, size=6)
x2 = np.random.randint(10, size=(3,4))
x3 = np.random.randint(10, size=(3,4,5))
print(x1)
print(x2)
print(x3)

[5 0 3 3 7 9]
[[3 5 2 4]
 [7 6 8 8]
 [1 6 7 7]]
[[[8 1 5 9 8]
  [9 4 3 0 3]
  [5 0 2 3 8]
  [1 3 3 3 7]]

 [[0 1 9 9 0]
  [4 7 3 2 7]
  [2 0 0 4 5]
  [5 6 8 4 1]]

 [[4 9 8 1 1]
  [7 9 9 3 6]
  [7 2 0 3 5]
  [9 4 4 6 4]]]


In [24]:
print('x3 ndim: ', x3.ndim)
print('x3 shape: ', x3.shape)
print('x3 size: ', x3.size)

x3 ndim:  3
x3 shape:  (3, 4, 5)
x3 size:  60


In [28]:
print(x3.itemsize)  # byte per size
print(x3.nbytes)    # 8 * 60 bytes


8
480


In [29]:
print(x1)
print(x1[3])
print(x1[-1])


[5 0 3 3 7 9]
3
9


In [30]:
print(x2)
print(x2[2,0])
print(x2[2,-1])

[[3 5 2 4]
 [7 6 8 8]
 [1 6 7 7]]
1
7


In [32]:
#x[start:stop:step]

x = np.arange(10)
print(x)
print(x[:5])
print(x[5:])
print(x[4:7])
print(x[::2])
print(x[1::2])

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4]
[5 6 7 8 9]
[4 5 6]
[0 2 4 6 8]
[1 3 5 7 9]


In [34]:
print(x[::-1]) # -1 : inverse order

[9 8 7 6 5 4 3 2 1 0]


In [35]:
print(x[5::-2])

[5 3 1]


In [36]:
print(x2)
print(x2[:2,:3])
print(x2[:3, ::2])

[[3 5 2 4]
 [7 6 8 8]
 [1 6 7 7]]
[[3 5 2]
 [7 6 8]]
[[3 2]
 [7 8]
 [1 7]]


In [37]:
print(x2[::-1, ::-1])

[[7 7 6 1]
 [8 8 6 7]
 [4 2 5 3]]


In [38]:
print(x2[:2,:2])

[[3 5]
 [7 6]]


In [39]:
x2[0,0] = 99
print(x2[:2,:2])

[[99  5]
 [ 7  6]]


In [43]:
## restructuring array
print(np.arange(1,10))
print(np.arange(1,10).shape)
print(np.arange(1,10).reshape(3,3))

[1 2 3 4 5 6 7 8 9]
(9,)
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [45]:
x = np.array([1,2,3])
print(x)
print(x.reshape((1,3)))

[1 2 3]
[[1 2 3]]


In [46]:
x[np.newaxis,:]

array([[1, 2, 3]])

In [48]:
x.reshape((3,1))

array([[1],
       [2],
       [3]])

In [50]:
x[:,np.newaxis]

array([[1],
       [2],
       [3]])

In [52]:
## to merge and split array
x= np.array([1,2,3])
y = np.array([3,2,1])
np.concatenate([x,y])

array([1, 2, 3, 3, 2, 1])

In [53]:
z = [99,99,99]
print(np.concatenate([x,y,z]))

[ 1  2  3  3  2  1 99 99 99]


In [56]:
grid = np.array([[1,2,3],[4,5,6]])
np.concatenate([grid, grid])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [57]:
np.concatenate([grid, grid], axis = 1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [58]:
y = np.array([[99], [99]])
np.hstack([grid, y])

array([[ 1,  2,  3, 99],
       [ 4,  5,  6, 99]])

In [60]:
np.vstack([x,grid])

array([[1, 2, 3],
       [1, 2, 3],
       [4, 5, 6]])

In [61]:
## to split array
## np.split, np.hsplit, np.vsplit


In [63]:
x = [1, 2,3, 99, 99, 3,2,1]
x1, x2, x3 = np.split(x, [3, 5])  # x[:3], x[3:5], x[5:]
print(x1, x2, x3)

[1 2 3] [99 99] [3 2 1]


In [ ]:
grid = np.arange(16).reshape((4,4))